// title --> require STRING
// image --> STRING (url) maybe have a default
// id --> auto-generated by mongo (no need to specific this)
// email --> STRING
// notes --> ARRAY

const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
    name: String,
    email: {
        required: true,
        type: string,
        match: [[/^\S+@\S+\.\S+$/, 'Not a valid email format.'],
        unique: true
    },
    notes: [{
        type: Schema.Types.ObjectId,
        ref: 'Note',
        default: []   // By default the user doesn't have any notes
    }]
})

const User = mongoose.model('user', userSchema);

module.exports = User;